# Generated by Django 4.0 on 2021-12-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallent',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='Tallent',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Tallent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ADMINS.tallent'),
        ),
    ]
