# Generated by Django 4.0 on 2021-12-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINS', '0002_alter_tallent_name_remove_userdetails_tallent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='un_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='media',
            name='un_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tallent',
            name='un_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='un_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
