# Generated by Django 4.0 on 2021-12-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINS', '0003_follower_un_deleted_media_un_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='User',
        ),
        migrations.AddField(
            model_name='follower',
            name='UserDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ADMINS.userdetails'),
        ),
    ]
