# Generated by Django 4.0 on 2021-12-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINS', '0004_remove_follower_user_follower_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
