# Generated by Django 4.0 on 2022-01-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINS', '0006_remove_media_tallent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(),
        ),
    ]
