# Generated by Django 4.0 on 2022-01-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINS', '0010_rename_user_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
